version: '3.9'

services:
  redis:
    image: redis:alpine
    # ports:
    #   - 6379:6379
    volumes:
      - ./private/redis:/data

  celery:
    build: .
    command: make celery
    environment:
      - CONFIG_FILE_NAME=config.docker.ini
    volumes:
      - ./private:/app/private
    depends_on:
      - redis

  flower:
    build: .
    command: make flower
    ports:
      - 5555:5555
    volumes:
      - ./private:/app/private
    depends_on:
      - redis
