version: '3.9'

services:
  redis:
    image: redis:alpine
    # ports:
    #   - 6379:6379
    volumes:
      - ./private/redis:/data

  celery:
    build: .
    command: make celery
    tty: true
    environment:
      - CONFIG_FILE_NAME=config.docker.ini
    volumes:
      - ./private:/app/private
      - ./s3_sync:/app/s3_sync
      - ./Makefile:/app/Makefile
    depends_on:
      - redis

  flower:
    build: .
    command: make flower
    tty: true
    ports:
      - 5555:5555
    environment:
      - CONFIG_FILE_NAME=config.docker.ini
    volumes:
      - ./private:/app/private
      - ./s3_sync:/app/s3_sync
      - ./Makefile:/app/Makefile
    depends_on:
      - redis
